import streamlit as st
import pandas as pd
from recommender import SkincareRecommender

# --- CONFIG ---
st.set_page_config(page_title="Expert Skincare System", layout="wide")

# Custom CSS for XAI Boxes
st.markdown("""
<style>
    .xai-box {
        background-color: #000000; 
        border-left: 5px solid #2196F3;
        padding: 10px;
        border-radius: 5px;
        margin-top: 10px;
        font-family: sans-serif;
        color: white;
    }
    .score-tag {
        background-color: #4CAF50;
        color: white;
        padding: 2px 8px;
        border-radius: 10px;
        font-size: 0.8em;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# --- INITIALIZE SYSTEM ---
@st.cache_resource
def load_system():
    return SkincareRecommender('export_skincare.csv')

recommender = load_system()

# --- SIDEBAR: FACTS COLLECTION ---
st.sidebar.title("Skincare Expert System")
st.sidebar.info("A Rule-Based Inference System based on dermatology ingredient knowledge.")

st.sidebar.header("User Profile")
name = st.sidebar.text_input("Name", "User")
skin_type = st.sidebar.selectbox("Skin Type", ['Normal', 'Dry', 'Oily', 'Combination', 'Sensitive'])
concern = st.sidebar.selectbox("Primary Concern", recommender.get_concerns())

st.sidebar.header("Constraints")
p_type = st.sidebar.selectbox("Product Category", recommender.get_product_types())
max_p = st.sidebar.slider("Max Budget (IDR)", 50000, 2000000, 300000)

# --- MAIN INFERENCE UI ---
st.title(f"Skin Diagnosis for: {name}")
st.write(f"Looking for **{p_type}** to treat **{concern}** for **{skin_type}** skin.")

if st.sidebar.button("Run Inference Engine"):
    with st.spinner("Consulting Knowledge Base..."):
        # CALL THE INFERENCE ENGINE
        results = recommender.inference(
            skin_type=skin_type,
            concern=concern,
            product_type=p_type,
            max_price=max_p
        )
    
    if not results.empty:
        st.success(f"Inference Successful. Found {len(results)} highly recommended products.")
        
        for idx, row in results.iterrows():
            with st.container():
                col1, col2 = st.columns([1, 3])
                
                with col1:
                    if pd.notna(row['picture_src']):
                        st.image(row['picture_src'], width=150)
                    else:
                        st.write("No Image")
                
                with col2:
                    # Product Header
                    st.markdown(f"### {row['product_name']} <span class='score-tag'>{int(row['final_score'])} pts</span>", unsafe_allow_html=True)
                    st.caption(f"{row['brand']} | {row['product_type']} | Rp {row['price_cleaned']:,.0f}")
                    
                    # XAI: EXPLANATION BOX
                    # This displays the "Why" generated by knowledge_base.py
                    st.markdown(f"""
                    <div class="xai-box">
                        <b>Explanation:</b><br>
                        {row['explanation_html']}
                    </div>
                    """, unsafe_allow_html=True)
                    
                    with st.expander("Product Details"):
                        st.write(row['notable_effects'])
                        st.write(row['description'])
                
                st.divider()
    else:
        st.error("No products found matching these strict rules. Try increasing your budget or changing the product category.")

else:
    st.info("Please set your parameters in the sidebar and click 'Run Inference Engine'.")